select
  {{ entity_key('player', 'provider_source', 'player_identity') }} as player_key,
  source_player_id,
  provider_source,
  provider_player_id,
  slug,
  full_name,
  normalized_full_name,
  first_name,
  last_name,
  birth_date,
  age,
  nationality,
  primary_position,
  secondary_positions,
  team_name as current_team_name,
  team_provider_id as current_team_provider_id,
  league_name as current_league_name,
  league_provider_id as current_league_provider_id,
  market_value_eur,
  market_value_last_updated_at,
  is_active,
  metadata,
  created_at,
  updated_at
from {{ ref('stg_players') }}
